application: guestbook
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /styles
  static_dir: styles

- url: /scripts
  static_dir: scripts

- url: /partials
  static_dir: templates/partials

- url: .*
  script: main.app
  login: required

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: latest
